<?php
# This file was automatically generated by the MediaWiki 1.36.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Path of Exile Wiki";
$wgMetaNamespace = "Path_of_Exile_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";
$wgArticlePath = '/wiki/$1';

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://www.poewiki.net";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/images/c/cb/PoEWikiLogo.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "hello@poewiki.net";
$wgPasswordSender = "hello@poewiki.net";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "";
$wgDBuser = "";
$wgDBpassword = "";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings

$wgUseGzip = true;
$wgEnableSidebarCache = true;

$wgMainCacheType = CACHE_MEMCACHED;
$wgParserCacheType = CACHE_MEMCACHED; // optional

$wgMessageCacheType = CACHE_MEMCACHED; // optional
$wgMemCachedServers = [ '127.0.0.1:11211' ];

$wgSessionCacheType = CACHE_MEMCACHED; // optional

$wgUseCdn = true;
$wgCdnServers = [ '127.0.0.1', '192.168.0.1' ];
//Use $wgCdnServersNoPurge if you don't want MediaWiki to purge modified pages
//$wgCdnServersNoPurge = [ '192.168.0.2' ];

$wgUseFileCache = true; // default: false
$wgFileCacheDirectory = "$IP/cache"; // default: "{$wgUploadDirectory}/cache" which equals to "$IP/images/cache"

$wgInvalidateCacheOnLocalSettingsChange = true;

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en-gb";

$wgSecretKey = "";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "aca16426767848ab";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/3.0/";
$wgRightsText = "Creative Commons Attribution-NonCommercial 3.0 Unported";
$wgRightsIcon = "$wgScriptPath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['user']['suppressredirect'] = true;


$wgCookieSecure = 'true';
$wgForceHTTPS = "true";

$actions = array( 'edit', 'watch', 'unwatch', 'delete','revert', 'rollback',
  'protect', 'unprotect', 'markpatrolled', 'render', 'submit', 'history', 'purge', 'info' );
 
foreach ( $actions as $action ) {
  $wgActionPaths[$action] = "/wiki/$action/$1";
}
$wgActionPaths['view'] = "/wiki/$1";
$wgArticlePath = $wgActionPaths['view'];


## SEO changes

$wgEnableCanonicalServerLink = "true";
$wgNativeImageLazyLoading  = true;


# Namespaces

// Define constants for my additional namespaces.
define("NS_BUFF", 10000); // This MUST be even.
define("NS_BUFF_TALK", 10001); // This MUST be the following odd integer.
define("NS_PASSIVE_SKILL", 10002); // This MUST be even.
define("NS_PASSIVE_SKILL_TALK", 10003);
define("NS_MODIFIER", 10004); // This MUST be even.
define("NS_MODIFIER_TALK", 10005);
define("NS_MONSTER", 10006); // This MUST be even.
define("NS_MONSTER_TALK", 10007);
define("NS_STAT", 10008); // This MUST be even.
define("NS_STAT_TALK", 10009);
define("NS_SKILL", 10010); // This MUST be even.
define("NS_SKILL_TALK", 10011);
define("NS_AREA", 10012); // This MUST be even.
define("NS_AREA_TALK", 10013);
define("NS_GUIDE", 10014); // This MUST be even.
define("NS_GUIDE_TALK", 10015);
define("NS_MAP", 10016); // This MUST be even.
define("NS_MAP_TALK", 10017);



// Add namespaces.
$wgExtraNamespaces[NS_BUFF] = "Buff";
$wgExtraNamespaces[NS_BUFF_TALK] = "Buff_talk"; // Note underscores in the namespace name.
$wgExtraNamespaces[NS_PASSIVE_SKILL] = "Passive_Skill";
$wgExtraNamespaces[NS_PASSIVE_SKILL_TALK] = "Passive_Skill_talk";
$wgExtraNamespaces[NS_MODIFIER] = "Modifier";
$wgExtraNamespaces[NS_MODIFIER_TALK] = "Modifier_talk";
$wgExtraNamespaces[NS_MONSTER] = "Monster";
$wgExtraNamespaces[NS_MONSTER_TALK] = "Monster_talk";
$wgExtraNamespaces[NS_STAT] = "Stat";
$wgExtraNamespaces[NS_STAT_TALK] = "Stat_talk";
$wgExtraNamespaces[NS_SKILL] = "Skill";
$wgExtraNamespaces[NS_SKILL_TALK] = "Skill_talk";
$wgExtraNamespaces[NS_AREA] = "Area";
$wgExtraNamespaces[NS_AREA_TALK] = "Area_talk";
$wgExtraNamespaces[NS_GUIDE] = "Guide";
$wgExtraNamespaces[NS_GUIDE_TALK] = "Guide_talk";
$wgExtraNamespaces[NS_MAP] = "Map";
$wgExtraNamespaces[NS_MAP_TALK] = "Map_talk";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'OATHAuth' );
# wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
# wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'Cargo' );
wfLoadExtension( 'EmbedVideo' );

# End of automatically generated settings.
# Add more configuration options below.

wfLoadExtension( 'Widgets' );
wfLoadExtension( 'Variables' );
wfLoadExtension( 'LabeledSectionTransclusion' );

$wgPFEnableStringFunctions = true;

$wgEmailConfirmToEdit = true;

wfLoadExtension( 'Math' );
# wfLoadExtension( 'MetaDescriptionTag' );

# Captcha loading and settings

wfLoadExtensions([ 'ConfirmEdit', 'ConfirmEdit/hCaptcha' ]);
$wgHCaptchaSiteKey = '7c012c2a-ad1c-4dab-a5df-42df71adc268';
$wgHCaptchaSecretKey = '';
$wgCaptchaTriggers['createaccount'] = true;
$wgGroupPermissions['autoconfirmed']['skipcaptcha'] = true;
$ceAllowConfirmedEmail = true;

# Cargo

$wgCargoPageDataColumns[] = 'creationDate';
$wgCargoPageDataColumns[] = 'creator';
$wgCargoPageDataColumns[] = 'modificationDate';
$wgCargoPageDataColumns[] = 'categories';
$wgCargoPageDataColumns[] = 'isRedirect';
$wgCargoPageDataColumns[] = 'pageNameOrRedirect';

$wgAllowUserCss = true;
$wgAllowUserJs = true;

wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );
$wgCirrusSearchServers = [ 'localhost' ];
$wgSearchType = 'CirrusSearch';

wfLoadExtension( 'RSS' );
$wgRSSUrlWhitelist = [ 'http://www.pathofexile.com/news/rss', ];
$wgRSSAllowLinkTag = true;
$wgRSSAllowImageTag = true;

# wfLoadExtension( 'MobileFrontend' );
# wfLoadSkin( 'MinervaNeue' );
# $wgMFDefaultSkinClass = 'Vector';
# $wgMFMobileHeader = 'X-WAP';
# $wgMFAutodetectMobileView = true;

$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp', 'svg', 'bmp' ];
$wgAllowTitlesInSVG = true;
$wgSVGConverter = 'ImageMagick';

$wgCSPHeader = [
  'default-src' => ['wikimedia.org']
];
$wgBreakFrames = true;

wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'DismissableSiteNotice' );